# Generated by Django 5.2.8 on 2025-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_choice_quiz_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
